databases:
  - name: AHLE
    databaseName: ahle_auction_production
    user: ahle_db_user

services:
  - type: web
    name: ahle_auction_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AHLE
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false